2025-02-19 16:36:33,186 - ERROR - Error processing test cases: [Errno 2] No such file or directory: 'data/generated_test_cases.json'
2025-02-19 16:37:07,864 - INFO - Backup created: key_test.json.4731798adcaa4e6d9efbbc27693034bb.bak
2025-02-19 16:37:07,866 - INFO - Successfully saved updated test cases to key_test.json
